// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bscpkvttjxpeprzljonj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzY3BrdnR0anhwZXByemxqb25qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MDgwNzUsImV4cCI6MjA2MTA4NDA3NX0.-6jO-wv2ivhw49HqpRKuaJX3-tFLc0aQhzj-JuuU9So";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);